kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/longhorn
parameters:
  fsType: "ext4"
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  baseImage: ""
#reclaimPolicy: Delete
reclaimPolicy: Retain
