kind: Namespace
apiVersion: v1
metadata:
  name: nfs-client01
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: nfs-client-sa01
  namespace: nfs-client01
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-client01-runner
  namespace: nfs-client01
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-client01
  namespace: nfs-client01
subjects:
  - kind: ServiceAccount
    name: nfs-client-sa01
    namespace: nfs-client01
roleRef:
  kind: ClusterRole
  name: nfs-client01-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client01
  namespace: nfs-client01
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-nfs-client01
  namespace: nfs-client01
subjects:
  - kind: ServiceAccount
    name: nfs-client-sa01
    # replace with namespace where provisioner is deployed
    namespace: nfs-client01
roleRef:
  kind: Role
  name: leader-locking-nfs-client01
  apiGroup: rbac.authorization.k8s.io
