kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-client01
  namespace: nfs-client01
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  selector:
    matchLabels:
      nfs-client-provisioner: nfs-client01
  resources:
    requests:
      storage: 10Mi
