kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs01-test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client01-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Mi
