apiVersion: v1
kind: Namespace
metadata:
  name:  rook-nfs1
---
# A default storageclass must be present
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-rlh-claim01
  namespace: rook-nfs1
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: rook-nfs-srv1
  namespace: rook-nfs1
spec:
  replicas: 1
  exports:
  - name: nfs-share01
    server:
      clients: all
      accessMode: ReadWrite
      squash: "none"
    # A Persistent Volume Claim must be created before creating NFS CRD instance.
    persistentVolumeClaim:
      claimName: nfs-rlh-claim01
