kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-client02
  labels: 
    nfs-client-provisioner: nfs-client02
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=4.1
  nfs:
    # get path and external IP from NFS service in cluster02/deploy/05-rook-nfs
    server: 192.168.92.42
    path: /nfs-rlh-claim02
