kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-client02-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: cluster.local/nfs-client02     # must match deployment's env 'PROVISIONER_NAME'
parameters:
  archiveOnDelete: "true"
mountOptions:
- vers=4.1
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
