kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-client03
  labels: 
    nfs-client-provisioner: nfs-client03
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=4.1
  nfs:
    server: 192.168.92.42
    path: /nfs-rlh-claim03
