kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs03-test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client03-sc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Mi
